services:
  - type: web
    name: keycloak
    env: docker
    plan: starter
    envVars:
      - key: KC_HOSTNAME_URL
        value: https://auth.ainuma.com
      - key: KC_HOSTNAME_ADMIN_URL
        value: https://auth.ainuma.com
      - key: KC_PROXY_HEADERS
        value: xforwarded
      - key: KC_HTTP_ENABLED
        value: "true"
    startCommand: >
      /opt/keycloak/bin/kc.sh start
      --hostname-url=${KC_HOSTNAME_URL}
      --hostname-admin-url=${KC_HOSTNAME_ADMIN_URL}
      --proxy-headers=${KC_PROXY_HEADERS}
      --http-enabled=${KC_HTTP_ENABLED}
      --http-port=${PORT}
      --http-host=0.0.0.0
