services:
  - type: web
    name: keycloak
    env: docker
    plan: starter
    envVars:
      - key: KC_HOSTNAME_URL
        value: https://auth.ainuma.com
      - key: KC_HOSTNAME_ADMIN_URL
        value: https://auth.ainuma.com
      - key: KC_PROXY_HEADERS
        value: xforwarded
      - key: KC_HTTP_ENABLED
        value: "true"

